# Generated by Django 5.1 on 2024-09-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='like_new',
        ),
    ]
